# Generated by Django 5.1.4 on 2025-01-09 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Ponto Turístico')),
                ('categoria', models.PositiveIntegerField(choices=[(1, 'Praia'), (2, 'Bar'), (3, 'Museu'), (4, 'Igreja'), (5, 'Praça'), (6, 'Mercado'), (7, 'Teatro'), (8, 'Parque'), (9, 'Restaurante'), (10, 'Café'), (11, 'Feira'), (12, 'Trilha'), (13, 'Shopping'), (14, 'Centro Cultural'), (15, 'Espaço Público'), (16, 'Rio')], verbose_name='Nome do Ponto Turístico')),
                ('descricao', models.TextField(verbose_name='Descrição do Ponto Turístico')),
                ('site', models.URLField(verbose_name='URL do Ponto Turístico')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto do Ponto Turístico')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, choices=[('PA', 'Pará'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=255, null=True, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Ponto Turístico',
                'verbose_name_plural': 'Pontos Turísticos',
                'db_table': 'ponto_turistico',
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Favoritos', to=settings.AUTH_USER_MODEL)),
                ('ponto_turistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pontoturistico')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'db_table': 'favorito',
            },
        ),
    ]
